version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install -g serve
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Build complete"
      - cd ..
      - echo "Zipping build artifacts for CodeDeploy..."
      - zip -r react-build.zip frontend/build appspec.yml scripts/
artifacts:
  files:
    - react-build.zip
  discard-paths: no
